comment: |
  Спасибо тебе огромное человеческое ✨❤️

  <picture><img width="400" src="https://github.com/smir-ant/smir-ant/assets/84059957/7d3ac67a-3523-4a67-8016-e706d2544fe9"></picture>
  
labels:
  '2 / 5':
    - '2 \(Плохо\)'
  '3 / 5':
    - '3 \(Ну\.\.\.\)'
  '4 / 5':
    - '4 \(Хорошо\)'
  '5 / 5':
    - '5 \(Отлично\)'
  '5+ / 5':
    - '5\+ \(Храни тебя господь\)'
  'спасибо за отзыв ❤️':
    - 'Отзыв'
    - 'Оценка'
  # 'Формат: видеокурс':
  #   - 'Видеокурс'
  'Формат: групповые занятия':
    - 'Оффлайн групповые занятия'
    - 'Онлайн групповые занятия'
  'Формат: индивидуальные занятия':
     - 'Онлайн индивидуальные занятия'

  