name: ะัะทัะฒ ะพ ะผะพะตะน ัะฐะฑะพัะต ะผะพะถะฝะพ ะพััะฐะฒะธัั ะทะดะตัั
description: ะขะพะปัะบะพ ะดะฐะฒะฐะน ะดะพะณะพะฒะพัะธะผัั, ะฟะธัะธ ัะตััะฝะพ ะธ ะธัะบัะตะฝะฝะต, ะปะฐะดะฝะพ? |
title: "ะัะทัะฒ"
# labels: ["ัะฟะฐัะธะฑะพ ะทะฐ ะพัะทัะฒ โค๏ธ"]
# assignees: ["smir-ant"]

body:
  - type: markdown
    attributes:
      value: |
        ะกะฟะฐัะธะฑะพ, ััะพ ะฝะฐัะตะป/ะฝะฐัะปะฐ ะฒัะตะผั ะฝะฐ ัะพ ััะพะฑั ะพััะฐะฒะธัั ะพัะทัะฒ. ะญัะพ ะฝะต ะทะฐะนะผัั ะผะฝะพะณะพ ะฒัะตะผะตะฝะธ!

  - type: input
    id: name
    attributes:
      label: ะะผั ะธ ะคะฐะผะธะปะธั
      description: ะะฝะพะฝะธะผะฝะพััั ััะพ ะบัััะพ, ะฝะพ ั ะฑั ัะพัะตะป ะทะฝะฐัั ะบัะพ ะพััะฐะฒะปัะตั ะพัะทัะฒ ๐๐
      placeholder: ะะฒะฐะฝะพะฒ ะะฒะฐะฝ
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: ะคะพัะผะฐั ะทะฐะฝััะธะน
      description: ะะพะถะฝะพ ะฒัะฑะธัะฐัั ะฝะตัะบะพะปัะบะพ
      multiple: true
      options:
        # - ะะธะดะตะพะบััั
        - ะะฝะปะฐะนะฝ ะณััะฟะฟะพะฒัะต ะทะฐะฝััะธั
        - ะะฝะปะฐะนะฝ ะธะฝะดะธะฒะธะดัะฐะปัะฝัะต ะทะฐะฝััะธั
        - ะััะปะฐะนะฝ ะณััะฟะฟะพะฒัะต ะทะฐะฝััะธั
    validations:
      required: true

  - type: textarea
    id: review
    attributes:
      label: ะัััะตะฝะธะต, ะฟะพัะปะตะฒะบััะธะต, ะผะฝะตะฝะธะต
      description: ะะพะดะตะปะธัั, ััะพ ะดัะผะฐะตัั ะพะฑ ััะพะผ ะฒะฐัะตะผ ะะฝัะพะฝะต??
      placeholder: ะั, ัะฐั ั ะบะฐะบ ะฝะฐะฟะธัั ะฟะพะดัะพะฑะฝัะน ะพัะทัะฒ ะธ ะฟะพะดะตะปััั ะฒััะบะธะผ ะธ ัะพัะพะบ ะตัั ะผะพะถะตั ะบะฐะบะธั ะฟัะธะบัะตะฟะปั, ะฐ ะผะพะถะตั ะธ ะผะตะผะพะฒ ะดะฐะถะต... 
    validations:
      required: true

  - type: dropdown
    id: rating
    attributes:
      label: ะัะตะฝะบะฐ
      description: ะะพัะฐ ััะฐะฒะธัั ะพัะตะฝะบั ะฟัะตะฟะพะดั :)
      options:
        - 2 (ะะปะพัะพ)
        - 3 (ะั...)
        - 4 (ะฅะพัะพัะพ)
        - 5 (ะัะปะธัะฝะพ)
        - 5+ (ะฅัะฐะฝะธ ัะตะฑั ะณะพัะฟะพะดั)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: recomend
    attributes:
      label: ะะพัะพะฒ(-ะฐ) ะปะธ ัั ัะตะบะพะผะตะฝะดะพะฒะฐัั ะฑัะตะฝะด `๐๐๐๐ฃ๐๐๐ง ๐ธ๐๐ฅ๐๐ ๐๐๐๐๐๐๐๐ฃ๐๐ง๐๐๐` ะดััะณะธะผ?
      options:
        - ะะพะทะดะตัะถััั
        - ะฅะพัั ะธ ะฑัะดั
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>ะงะตัะตะท 15 ัะตะบ. ะฟะพัะปะต ะพัะฟัะฐะฒะปะตะฝะธั ะพัะทัะฒ ะฑัะดะตั ะพะฑัะฐะฑะพัะฐะฝ (ะฟัะธะปะตัะธั ะบะพะผะผะตะฝัะฐัะธะน ๐ฌ ะธ ะผะตัะบะธ ะฟัะพััะฐะฒัััั ๐ท๏ธ).
        ะะปั ะพัะฟัะฐะฒะปะตะฝะธั ะพัะทัะฒะฐ ะฝะฐะถะผะธ ะฝะฐ ะทะตะปัะฝัั ะบะฝะพะฟะพัะบั <picture><img width="100" src="https://github.com/user-attachments/assets/1c3c2b03-d0fc-485a-92f5-0a96c61f478c"></picture> ะฝะธะถะต.
        <br><h1 align="center">ะกะฟะฐัะธะฑะพ ะทะฐ ะพัะทัะฒ โค๏ธ</h1>
        <p align="center"><picture><img width="300" src="https://github.com/user-attachments/assets/05d53f26-ee31-44a3-bde3-dafe6b2d4edf"></picture></p>