name: Process the labels
on: 
  issues:
    types: [opened, edited]  # когда issue открывается или редактируется

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Add Labels
      uses: jimschubert/labeler-action@v2  # лучшие просто https://github.com/marketplace/actions/auto-labeler
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Handle Multiple Issues
      uses: Anmol-Baranwal/handle-multiple-issues@v1
      with:
        label: "несколько отзывов" # повесить метку как причину закрытия
        close: true  # закрыть issue
        issueNumber: true  # указать номер issue
        comment: "уже открыто тобой."  # вместо стандартного "is already opened by you."
        
    # Сохраню себе на память | закрытие issue текущего 
    # - name: Close Issue
    #   shell: bash
    #   run: |
    #     gh issue close -R "${{ github.repository }}" \
    #     --reason "completed" \
    #     ${{ steps.params.outputs.comment }} \
    #     "${{ github.event.issue.number }}"
    #   env:
    #     GH_TOKEN: ${{ github.token }}
